Adicionando a página da minha maravilhosa e modificando a index.html
reprograma/On3-projeto-final pull request #19
Opened 2019-12-20 02:18 UTC by meirylandmelo

Cintia, vai aparecer que teve mais alteração na index, mas foi a identação, que quando eu salvo ela corrige.

2019-12-22 16:07 UTC, lprimante approved these changes

2019-12-22 16:15 UTC, lprimante requested changes
Olá @meirylandmelo, tudo bem? Você instalou o plugin do VS Code que a Cintia sugeriu para que fosse evitado esse problema de indentação do código? 
Eu não tenho como aceitar seu projeto desse jeito pois o conflito me impede de mergea-lo ao restante, peço por gentileza que tente resolver para que sua página possa ser aceita. 
Obrigada!

2019-12-22 16:15 UTC, lprimante commented on index.html
> +</html>
Essa indentação está causando conflitos no index.html do site todo

2019-12-22 22:46 UTC, meirylandmelo commented
Oi @lprimante , eu instalei o EditorConfig e o Live Server como ela fez no início da aula. São esses os plugins a que você se refere?

2019-12-22 23:11 UTC, meirylandmelo commented
@lprimante ajuste a indentação e subi novamente, meu vscode estava indentando automaticamente ao salvar.

2020-01-16 14:45 UTC, lprimante commented
O único problema foi que você acabou mexendo no index além do lugar onde deveria e ainda sim vai rolar conflitos, o ideal é desfazer os seus commits e subir novamente o seu projeto. Como é um pouco mais delicado esse processo eu posso fazer aqui.

2020-01-16 14:52 UTC, meirylandmelo commented
Eu copiei a master do jeito que estava porque não tinha mais o original sem estar modificado, ai na master a Cintia já tinha feito o merge de outras meninas, será que foi por isso?

2020-01-16 14:55 UTC, lprimante commented
Pode ser que sim. Eu vou baixar aqui e dou uma olhada :)

2020-01-16 14:57 UTC, meirylandmelo commented
Certo.

2020-01-16 15:04 UTC, lprimante approved these changes

2020-01-16 15:07 UTC, meirylandmelo commented
Obrigada, Lu!

2020-01-16 15:09 UTC, merged